BOOTLOADER = rp2040
BOARD = GENERIC_RP_RP2040
MCU = RP2040

SRC += $(QUANTUM_DIR)/quantum.c

ARMV = 7
USE_FPU = yes
FLOAT_IMPLEMENTATION = newlib

SERIAL_DRIVER = vendor
WS2812_DRIVER = vendor
DFU_ARGS = -d 1209:bA42 -a 0 -R
DFU_SUFFIX_ARGS = -v 1209 -p bA42
PROGRAMMER = atmel_dfu

MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
MAGIC_ENABLE = yes
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
SPLIT_KEYBOARD = no

LTO_ENABLE = yes

# OLED display (SSD1306 128x32 via I2C, SCL=GP26, SDA=GP25)
OLED_ENABLE = yes
OLED_DRIVER = ssd1306

# Rotary encoder (A=GP27, B=GP29)
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

# LTO for size optimization
LTO_ENABLE = yes

# Size optimizations
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
